### ISSUE TITLE
Bug with this module takes us to 403 and forbidden images in BO

### ISSUE THREAD

**Issue by therampagerado** [thirtybees/watermark#2]
As discussed in the forum here:

https://forum.thirtybees.com/topic/5862-403-error-when-attempting-to-save-seo-urls-page/#comment-44562

and here:

https://forum.thirtybees.com/topic/5854-cant-see-enlarged-product-picteres-in-backoffice/#comment-44556

if the following code is present in .htaccess the website have 2 issues:

```
# start ~ module watermark section
<IfModule mod_rewrite.c>
Options +FollowSymLinks
RewriteEngine On
RewriteCond expr "! %{HTTP_REFERER} -strmatch '*://%{HTTP_HOST}*/admin******/*'"
RewriteRule [0-9/]+/[0-9]+\.jpg$ - [F]
</IfModule>
# end ~ module watermark section
```

1. Product images in Product can not be enlarged
2. When saving in SEO section BO gives 403

@getdatakick said it's not an app issue in one of the threads but maybe it's worth a second look?!

**Comment by Dh42** [comment]
A 403 error is almost 100% of the time generated from mod_security on the server. What you need to do, is set it off again, look at your mod_security logs, find the exception along with your IP address and either disable that rule or whitelist your IP address. I honestly have never seen a 403 error that was not generated by anything other than mod_security, although I am sure it happens.

**Comment by getdatakick** [comment]
The .htaccess rule basically says that if watermark module is enabled then nobody can access original images (unless they the request originates from administration page).

This is exactly what watermark module is supposed to do, right? To block access to original (non watermarked) images.

I suspect that your theme (or module) constructs path to original image manually to facilitate zoom effect. But that's wrong. The theme should use $link object to receive url for higher resolution images (use different image type).

Not sure why SEO saving should cause any issues.  Maybe `Options +FollowSymLinks` ??? I'm not sure why that's in there

**Comment by marktnz1** [comment]
Uninstalling the module does not remove the .htaccess code relating to the module.

Removing the .htaccess code above upon uninstall of the module would have solved the problem I had with 403 errors after I uninstalled the module.

**Comment by getdatakick** [comment]
> 

It does:
https://github.com/thirtybees/watermark/blob/b01df1bbcceafdb008d92a2d02f6d148635fbf13/watermark.php#L85-L89

If this didn't happen for you, then there must be other reasons, for example:

- permissions or ownership of the .htaccess file has changed sometimes in between the module installation and uninstallation
- module wasn't uninstalled properly, but simply deleted
- somebody modified .htaccess file and removed or modified delimiters that watermark module uses to detect borders of the section.

**Comment by marktnz1** [comment]
No Petr. Never assume others are to blame. I never touch code ever, now I've had to because this was not removed

**Comment by getdatakick** [comment]
> No Petr. Never assume others are to blame. I never touch code ever, now I've had to because this was not removed

I don't blame others. I look a the code and try to reason about why it wasn't executed. =

Code to remove .htaccess section exists in the module. This code works properly, I just tested it. If the section was not removed, then that means that this code was either not executed at all (module uninstall was not performed), or was executed but failed. If you indeed uninstalled the module properly, then something must have gone really bad. Either the write to the disk failed (permissions, etc.), or the section delimiters were not found in file. Is there some other explanation?

This is not blaming anyone, this is just explanation what must have happened.

**Comment by getdatakick** [comment]
I tested again. Maybe #3 is the root cause of your issue. I managed to reproduce by following steps:

1) install `watermark` module
2) uninstall `watermark` module
3) check that .htaccess does not contains watermark section (OK)
4) install `watermark` module
5) go to Preferences > SEO & URL, and hit Save
6) uninstall `watermark` module
7) check that .htaccess does not contains watermark section (FAILED)

The step 5 - saving in SEO & URL - removes leading empty line in .htaccess file. This empty line is part of section delimiter (see issue #3)

**Comment by marktnz1** [comment]
Ok thanks for testing further...sounds like youve sussed out the root cause...  The issue for me was fixed by deleting (actually commenting out) the code. So for me I was happy, just a case of ensuring that for others the problem is fixed also as the problem can be significant. Thank for getting it sorted and double testing.
